name: CI/CD

on:
  push:
    branches: [ 3-refactoring, master, dev ]
  pull_request:
    branches: [ 3-refactoring, master, dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework 4.7.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      
  test:
    
    
    runs-on: windows-latest
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
